#!/usr/bin/env python3
"""Regenerate this site's content from the single source of truth.

PROFILE.md (in the private pw-meta repo) is the authoritative "who I am". It is
projected into profile-readme/data/profile.json, and this script projects *that*
into the two places Hugo reads:

    data/authors/me.yaml     the profile: bio, education, internship, skills, ...
    content/projects/<id>/   one folder per research project

Run it after any change to profile.json, then commit the result. Nothing here is
hand-maintained; editing me.yaml directly means the next run overwrites you.

    tools/sync-profile.py            regenerate
    tools/sync-profile.py --check    exit non-zero if the checked-in files are stale

Cover images (content/projects/*/featured.png) are NOT touched — they are assets,
and regenerating content must not delete them.
"""

import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
SRC = HERE.parent / "profile-readme" / "data" / "profile.json"


def q(s: str) -> str:
    """YAML-safe scalar."""
    return json.dumps(s, ensure_ascii=False)


def build_author(d: dict) -> str:
    ident = d["identity"]
    linkedin = next(l["url"] for l in d["links"] if l["label"] == "LinkedIn")

    # No `level` on any skill: the theme only draws a progress bar when a level is
    # present, and a self-assigned 4/5 on "Python" is noise.
    skills = ""
    for group in d["skills"]:
        if group["group"] == "Spoken":  # rendered by the languages block instead
            continue
        skills += f"  - name: {q(group['group'])}\n    items:\n"
        for item in group["items"]:
            skills += f"      - label: {q(item)}\n"

    return f"""# GENERATED by tools/sync-profile.py from profile-readme/data/profile.json.
# Do not hand-edit: edit PROFILE.md, mirror it into profile.json, then re-run.
schema: hugoblox/author/v1
slug: me
is_owner: true
name:
  display: {q(ident['display'])}
  given: Tianlang
  family: Chen
  alternate: {q(ident['name_zh'])}
role: {q(ident['role'])}
bio: |
  {d['bio_long'][0]}

affiliations:
  - name: {q(ident['affiliation'])}
    url: https://umich.edu

links:
  - icon: at-symbol
    url: mailto:{ident['email']}
    label: E-mail Me
  - icon: brands/github
    url: https://github.com/{ident['github']}
  - icon: brands/linkedin
    url: {linkedin}

interests:
  - AI for Science
  - AI for Decision Making
  - Genomic Foundation Models
  - LLM Workflows & Agents

education:
  - degree: B.S.E. Data Science
    institution: University of Michigan, Ann Arbor
    start: 2025-09-01
    summary: |
      Machine Learning; Computer Graphics & Generative Models; Computational
      Linguistics; Algorithms & Data Structures; Probability & Statistics.
  - degree: Mechanical Engineering (Dual Degree)
    institution: Shanghai Jiao Tong University, UM-SJTU Joint Institute
    start: 2023-09-01
    end: 2025-05-31
    summary: |
      Applied Linear Algebra; Dynamical Systems; Design & Manufacturing;
      Dynamics & Vibrations.

experience:
  - role: WeCom Full-Stack Developer, Intern
    org: Mars Asia — Global IT Service Center
    start: 2024-06-01
    end: 2025-05-31
    summary: |
      Full-stack WeCom development in JavaScript, Node.js and Vue.js. API and
      interface work, data migration, and cross-platform retrieval. Built the
      automation that kept operations continuous through a system migration.

skills:
{skills}
languages:
  - name: English
    label: Professional
  - name: Mandarin
    label: Native
  - name: Cantonese
    label: Native

awards:
  - title: Honorable Mention, MCM/ICM
    awarder: COMAP Mathematical Contest in Modeling
    date: "2025-01-15"
    icon: hero/trophy
  - title: Teaching Assistant, General Physics
    awarder: Shanghai Jiao Tong University
    date: "2025-05-01"
    icon: hero/academic-cap
  - title: Teaching Assistant, English Academic Writing
    awarder: Shanghai Jiao Tong University
    date: "2025-03-01"
    icon: hero/academic-cap
"""


def project_pages(d: dict) -> dict:
    """slug -> index.md. One per research entry, plus the visible placeholder."""
    pages = {}
    for r in d["research"]:
        pages[r["id"].lower()] = f"""---
title: {q(r['title'])}
summary: {q(r['hook'])}
date: 2026-01-01
tags:
  - Research
---

{r['detail']}
"""
    # The trailing card. Headroom the visitor can see, not a silent gap.
    pages["more"] = f"""---
title: {q(d['labels']['research_more'])}
summary: More work is on the way — this slot exists so the room to grow is visible.
date: 2025-12-31
tags:
  - Research
---

More projects are in progress.
"""
    return pages


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report staleness without writing anything")
    args = ap.parse_args()

    if not SRC.exists():
        print(f"error: source of truth not found at {SRC}", file=sys.stderr)
        return 1

    d = json.loads(SRC.read_text())
    targets = {HERE / "data" / "authors" / "me.yaml": build_author(d)}
    for slug, body in project_pages(d).items():
        targets[HERE / "content" / "projects" / slug / "index.md"] = body

    stale = [p for p, body in targets.items()
             if not p.exists() or p.read_text() != body]

    if args.check:
        if stale:
            for p in stale:
                print(f"STALE: {p.relative_to(HERE)}", file=sys.stderr)
            print("run tools/sync-profile.py", file=sys.stderr)
            return 1
        print("up to date")
        return 0

    for p, body in targets.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    print(f"regenerated {len(targets)} file(s) from {SRC.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
